--- #YAML:1.0
name:               VK-MP3
version:            0.09
abstract:           searches for mp3 on vkontakte.ru, also known as vk.com.
author:
    - Alexandr Alexeev <eax@cpan.org>
license:            perl_5
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:               2.47
    HTML::Entities:       3.69
    JSON::XS:             2.32
    LWP:                  6.04
    LWP::Protocol::https:  6.03
    MP3::Info:            1.24
    perl:                 5.008008
    Test::Mock::LWP:      0.06
    Text::Unidecode:      0.04
    URI::Escape:          3.31
resources:
    bugtracker:  https://github.com/afiskon/p5-vk-mp3/issues
    homepage:    http://eax.me/vk-get-mp3/
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/afiskon/p5-vk-mp3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
