---
abstract: 'search for mp3 on vk.com'
author:
  - 'Alexandr A Alexeev <afiskon@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: VK-MP3
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Entities: 3.69
  LWP: 6.04
  LWP::Protocol::https: 6.03
  Test::Mock::LWP: 0.06
  URI::Escape: 3.31
version: 0.01
